project_id = "mqixrtmnkogdpsaqosfm"

[functions.citizenship-interview]
verify_jwt = true

[functions.generate-vocabulary-audio]
verify_jwt = true

[functions.generate-vocabulary-images]
verify_jwt = true

[functions.pronunciation-analysis]
verify_jwt = true

[functions.virtual-coach-chat]
verify_jwt = true
